"""add_color_to_product_images

Revision ID: 8a16e9f9398f
Revises: 40d4e15ba01d
Create Date: 2026-07-04 06:45:00.068229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a16e9f9398f'
down_revision: Union[str, None] = '40d4e15ba01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('color', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_product_images_color'), 'product_images', ['color'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_color'), table_name='product_images')
    op.drop_column('product_images', 'color')
    # ### end Alembic commands ###
